/**
 * Soul Templates - Predefined SOUL.md content for each assistant type.
 *
 * Source of truth:
 * - convex/ai/souls/assistants/<assistantId>/soul.md
 *
 * Synced into:
 * - convex/ai/souls/client.ts (generated by scripts/sync-ai-prompts.mjs)
 *
 * This module is intentionally client-safe (no fs/path usage).
 */

export * from "./client";
